#!/bin/bash
# Shamelessly stolen from https://github.com/mystor/machwrapper.
#
# $ curl -sSL https://raw.githubusercontent.com/kashav/moz/master/scripts/mach > mach
# $ chmod +x mach
# $ sudo mv mach usr/local/bin/

DIR="$PWD"
while [[ ! -e "$DIR/mach" ]]; do
    if [[ "$DIR" == '/' ]]; then
        echo "ERROR: unable to locate mach in this directory or parent directories" >&2
        exit 1
    fi
    DIR=$(dirname "$DIR")
done
MACH="$DIR/mach"

"$MACH" $*
exit $?
